[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gcrl-landscapes"
dynamic = ["version"]
description = ""
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "Jan Malte Töpperwien", email = "m.toepperwien@protonmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "gymnasium",
  "gymnasium[mujoco]",
  "ogbench @ git+https://github.com/CrunchyFlakes/ogbench",
  "tqdm",
  "flax",
  "numpy",
  "jax[cuda12]",
  "wandb",
  "scipy",
  "GitPython",
  "toml",
  "gpflow",
  "ConfigSpace",
  "autorl_landscape @ git+https://github.com/automl/AutoRL-Landscape.git",
  "arlbench",
  "gymnasium",
  "huggingface_hub",
  "seaborn",
]

[project.urls]
Documentation = "https://github.com/LUH-AI/GCRL-Landscapes#readme"
Issues = "https://github.com/LUH-AI/GCRL-Landscapes/issues"
Source = "https://github.com/LUH-AI/GCRL-Landscapes"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.version]
path = "src/gcrl_landscapes/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/gcrl_landscapes tests}"

[tool.coverage.run]
source_pkgs = ["gcrl_landscapes", "tests"]
branch = true
parallel = true
omit = [
  "src/gcrl_landscapes/__about__.py",
]

[tool.coverage.paths]
gcrl_landscapes = ["src/gcrl_landscapes", "*/gcrl-landscapes/src/gcrl_landscapes"]
tests = ["tests", "*/gcrl-landscapes/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.ruff]
extend-exclude = [ "src/gcrl_landscapes/plots/triple_gp.py", ]
