hyperparameters:
  lr:
    type: uniform_float
    lower: 1e-6
    upper: 1e-3
    default_value: 3e-4
  batch_size:
    type: uniform_float
    lower: 1
    upper: 4096
    default_value: 1024
  latent_dim:
    type: uniform_float
    lower: 8
    upper: 4096
    default_value: 512
  discount:
    type: uniform_float
    lower: 0.8
    upper: 0.9999
    default_value: 0.99
  const_std:
    type: categorical
    choices: [ true, false ]
    default_value: true
  value_geom_sample:
    type: categorical
    choices: [ true, false ]
    default_value: true
  actor_p_trajgoal:
    type: uniform_float
    lower: 0.0
    upper: 1.0
    default_value: 1.0
  actor_p_curgoalshare:
    type: uniform_float
    lower: 0.0
    upper: 1.0
    default_value: 1.0
  actor_geom_sample:
    type: categorical
    choices: [ true, false ]
    default_value: false
