time = "2025-12-23T16:56:16"

[arguments]
logdir = "PosixPath('logs_convergence/HIQL_antmaze-large-explore40navigate-v0_1c_discount-actor_p_trajgoal')"
phase = 1000000
configuration_index = 0
seed = 4
tasks_per_node_parallel = 5

[git]
commit = "6a56c80dce10870303f367aae977488b203d5c74"
branch = "main"
