time = "2025-12-30T17:53:23"

[arguments]
agent = "HIQL"
final_phase = 1000000
final_performance_percentage = 95
phase_percentages = [ 100,]
datasets = [ "antmaze-large-navigate-v0",]
n_configurations = 1
hyperparameters = [ "discount", "actor_p_trajgoal",]
extra_eval_steps = [ 1000, 2500, 5000, 7500, 10000, 20000, 30000, 40000, 50000, 75000, 100000, 150000, 200000, 300000, 400000, 500000, 600000, 700000, 800000, 900000, 100000,]
eval_episodes = 10
seed = 0
logdir = "PosixPath('logs_convergence/HIQL_antmaze-large-navigate-v0_1c_discount-actor_p_trajgoal')"
final_step_is_phase = true
actor_loss = "awr"
func = "<function run_setup at 0x14782dd0bac0>"
phases = [ 1000000,]

[git]
commit = "2f968f7ecd8dab9f195902b9e31fae355884bed0"
branch = "main"
