eval_episodes: 50
tasks_per_node_parallel: 1

hydra:
  run:
    dir: ./smac_log/${agent_name}/${env}
  sweep:
    dir: ./smac_log/${agent_name}/${env}
  sweeper:
    n_trials: 128
    sweeper_kwargs:
      optimizer_kwargs:
        smac_facade:
          _target_: smac.facade.hyperparameter_optimization_facade.HyperparameterOptimizationFacade
          _partial_: true
        intensifier:
          _target_: smac.facade.hyperparameter_optimization_facade.HyperparameterOptimizationFacade.get_intensifier
          _partial_: true
          # [TODO: although SMAC receives this intensifier, no configuration is called with a seed!=0]
          max_config_calls: 5
        scenario:
          n_trials: ${hydra.sweeper.n_trials}
          seed: ${seed}
          deterministic: true
          use_default_config: true
          output_directory: ${hydra.sweep.dir}
