eval_episodes: 50
tasks_per_node_parallel: 1

hydra:
  run:
    dir: ./smac_log/${agent_name}/${env}/${phase}
  sweep:
    dir: ./smac_log/${agent_name}/${env}/${phase}
  sweeper:
    n_trials: 128
    sweeper_kwargs:
      seeds: [0, 1, 2, 3, 4]
      optimizer_kwargs:
        smac_facade:
          _target_: smac.facade.hyperparameter_optimization_facade.HyperparameterOptimizationFacade
          _partial_: true
        scenario:
          n_trials: ${hydra.sweeper.n_trials}
          seed: ${seed}
          deterministic: true
          use_default_config: true
          output_directory: ${hydra.sweep.dir}
