eval_episodes: 50
tasks_per_node_parallel: 4

hydra:
  sweeper:
    n_trials: 128
    budget_variable: training_steps
    sweeper_kwargs:
      optimizer_kwargs:
        smac_facade:
          _target_: smac.facade.multi_fidelity_facade.MultiFidelityFacade
          _partial_: true
        intensifier:
          _target_: smac.facade.multi_fidelity_facade.MultiFidelityFacade.get_intensifier
          _partial_: true
          eta: 3
          n_seeds: 3
        scenario:
          n_trials: ${hydra.sweeper.n_trials}
          seed: ${seed}
          min_budget: 50000
          max_budget: 1000000
          deterministic: true
          use_default_config: true
          n_workers: 4
          output_directory: ${hydra.sweep.dir}
