time = "2025-06-27T18:58:18"

[arguments]
logdir = "PosixPath('logs_convergence/GCBC_antmaze-large-navigate-v0_1c_discount-actor_p_trajgoal')"
phase = 1000000
configuration_index = 0
seed = 2
tasks_per_node_parallel = 5

[git]
commit = "016552753321c5091f48d21965dbb979b08418a4"
branch = "temp"
