time = "2025-12-30T19:47:08"

[arguments]
logdir = "PosixPath('logs_convergence/QRL_antmaze-teleport-navigate-v0_1c_discount-actor_p_trajgoal')"
phase = 1000000
configuration_index = 0
seed = 3
tasks_per_node_parallel = 1

[git]
commit = "2f968f7ecd8dab9f195902b9e31fae355884bed0"
branch = "main"
